### ISSUE TITLE
MAME sound after saving

### ISSUE THREAD

**Issue by Driche** [kaz321123/Mame2003-Samples#1]
While the MAME games create save states and the sound is good when playing the game, after I go back to play a saved game, the sound is lacking, (the music is on for the game, but action sounds are not heard)

**Comment by kaz321123** [comment]
I think save states don't work very well for mame.  Some games don't save at all (like sf2ce), while others like pac-man will go back to where you were-but the sound won't work for a few seconds.

**Comment by Driche** [comment]
That's what I'm thinking too. Maybe there will be a fix in the future. For now I guess just add as many credits as you can and see how far you get! Thanks for the help!
